name: Build Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Packages
        run: |
          brew update --quiet || true

          export HOMEBREW_NO_AUTO_UPDATE=1
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          brew install openssl ninja
      - name: Build
        run: |
          mkdir build && cd build
          cmake -G Ninja -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ..
          ninja
